version: '3.7'

services:
  backend:
    container_name: container_backend
    image: image_backend
    build:
      context: .
      dockerfile: containers/Dockerfile
    env_file: containers/env
    entrypoint: >
      bash -c "
      rm -f tmp/pids/server.pid
      && bundle
      && bundle exec rails s -b 0.0.0.0 -p 3000"
    ports:
      - 3000:3000
    volumes:
      - .:/opt/app
    networks:
      - default
  db:
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - default
  mail_server:
    image: schickling/mailcatcher:latest
    ports:
      - "1025:1025"
      - "1080:1080"
volumes:
  db-data:
